server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de producto
          uri: lb://movies-api #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/movies/**
        - id: billRoute #Identificando la ruta del service de producto
          uri: lb://ms-bills #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/bills/**
