server:
  port: 8080
  
spring:
  cloud:
    gateway:
      default-filters:
        - name: TokenRelay
      routes:
        - id: moviesRoute #Identificando la ruta del service de producto
          uri: http://localhost:8083/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/movies/**
        - id: billsRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/bills/**
        - id: usersRoute #Identificando la ruta del service de producto
          uri: http://localhost:8085/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/users/**
